FROM docker.elastic.co/logstash/logstash:8.13.4
RUN rm -f /usr/share/logstash/pipeline/logstash.conf
COPY logstash/pipeline/ /usr/share/logstash/pipeline/
COPY logstash/config/ /usr/share/logstash/config/